### ISSUE TITLE
Fatal Error on Plugin activate

### ISSUE THREAD

**Issue by Amin-Noorani** [veronalabs/rabbit#2]
Hello.
After cloning the repository and creating the plugin.php file, I encounter a Fatal error. I checked and found that the namespace changed in the src/Utils/Singleton.php file. In the repository, the namespace is Rabbit\Utils, but after cloning, it changes to Backyard\Utils, causing the class to be unrecognized in the plugin.php file.

![image](https://github.com/veronalabs/rabbit/assets/81982993/77aae295-aa07-4a01-9596-9137f0da83b2)
![image](https://github.com/veronalabs/rabbit/assets/81982993/572f984d-c969-41aa-904c-b2aaffbc7790)

**Comment by mostafasoufi** [comment]
Weird indeed, please make sure you're closing the correct repository `git@github.com:veronalabs/rabbit.git` and also the correct composer command package `composer require veronalabs/rabbit`

I'd prefer to clear your composer cache before cloning/installing the package.

```
composer clear-cache
```
